services:
  postgres:
    image: postgres:16-alpine
    container_name: kms-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: kms
      POSTGRES_USER: kms
      POSTGRES_PASSWORD: kms_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kms']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: kms-pgadmin
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kms.local
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
